version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: Greeting
          command: ls -ltrh

      - run:
          name: Print the Current Time
          command: echo date
