version: 2
jobs:
  build:
    docker:
      - image: docker/compose

    steps:
      - checkout

      - setup_remote_docker:   # (2)
          docker_layer_caching: true # (3)
      
      - run:
          name: View folders
          command: | 
            set -x 
            ls -ltrh


      - run:
          name: Build & UnitTest
          command: |
           docker build -t accountownerapp:B1 -f Dockerfile .
