version: 2
jobs:
  build:
    docker:
      - image: docker/compose

    steps:
      - checkout

      - setup_remote_docker:   # (2)
          docker_layer_caching: false # (3)
      
      - run:
          name: View folders
          command: | 
            set -x 
            ls -ltrh


      - run:
          name: Build & UnitTest
          command: |
           docker build -t yanivomc/piplineapp:B$CIRCLE_BUILD_NUM -f Dockerfile .
           echo "Starting Integration Test"
           docker build -t yanivomc/integration-piplineapp:B$CIRCLE_BUILD_NUM -f Dockerfile.Integration .
      - run:
          name: Pusblish UT Reports
          command: |
           docker run -d --rm --name app1 yanivomc/piplineapp:B$CIRCLE_BUILD_NUM
           docker cp app1:/TestResults TestResults
           docker stop app1
           apk add --no-cache ca-certificates
           pwd
           ls -ltrh

      - run:
          name: Push to Repo
          command: |
           docker login -u $DOCKER_USER -p $DOCKER_PASS 
           docker push yanivomc/piplineapp:B$CIRCLE_BUILD_NUM
           docker tag yanivomc/piplineapp:B$CIRCLE_BUILD_NUM yanivomc/piplineapp:latest
           docker push yanivomc/piplineapp:latest
           docker tag yanivomc/integration-piplineapp:B$CIRCLE_BUILD_NUM yanivomc/integration-piplineapp:latest
           docker push yanivomc/integration-piplineapp:latest

      - run:
          name: Integration Tests Latest Version
          command: |
           docker-compose -f docker-compose.integration.yml up --force-recreate --abort-on-container-exit
      
      - run:
          name: Update K8S Deployment Yaml
          command: |
            sed -i 's/piplineapp:.*/piplineapp:'"$CIRCLE_BUILD_NUM"'/g' k8s/deployments/deployments.yaml



      - store_test_results:
          path: ./TestResults
