version: 2
jobs:
  build:
    machine: true
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: Greeting
          command: ls -ltrh

      - build:
          name: Build First docker
          command: docker build -t yanivomc/netapp:$CIRCLE_BUILD_NUM .
