version: 2
jobs:
  build:
    docker:
      - image: yanivomc/docker-compose:latest 

    steps:
      - checkout

      - setup_remote_docker:   # (2)
          docker_layer_caching: false # (3)
      
      - run:
          name: View folders
          command: | 
            set -x 
            ls -ltrh


      - run:
          name: Build & UnitTest
          command: |
           docker build -t yanivomc/piplineapp:B$CIRCLE_BUILD_NUM -f Dockerfile .
           echo "Starting Integration Test"
           docker build -t yanivomc/integration-piplineapp:B$CIRCLE_BUILD_NUM -f Dockerfile.Integration .
      - run:
          name: Pusblish UT Reports
          command: |
           docker run -d --rm --name app1 yanivomc/piplineapp:B$CIRCLE_BUILD_NUM
           docker cp app1:/TestResults TestResults
           docker stop app1
           apk add --no-cache ca-certificates
           pwd
           ls -ltrh

      - run:
          name: Push to Repo
          command: |
           docker login -u $DOCKER_USER -p $DOCKER_PASS 
           docker push yanivomc/piplineapp:B$CIRCLE_BUILD_NUM
           docker tag yanivomc/piplineapp:B$CIRCLE_BUILD_NUM yanivomc/piplineapp:latest
           docker push yanivomc/piplineapp:latest
           docker tag yanivomc/integration-piplineapp:B$CIRCLE_BUILD_NUM yanivomc/integration-piplineapp:latest
           docker push yanivomc/integration-piplineapp:latest

      - run:
          name: Integration Tests Latest Version
          command: |
           docker-compose -f docker-compose.integration.yml up --force-recreate --abort-on-container-exit
      
      - run:
          name: Update K8S Deployment Yaml
          command: |
            git config user.email "yanivomc@gmail.com"
            git config user.name "yanivomc"
            git pull
            sed -i 's/piplineapp:B.*/piplineapp:B'"$CIRCLE_BUILD_NUM"'/g' k8s/deployments/deployments.yaml

      - run:
          name: push Deployment Yaml changes
          command: |
            git add .
            git commit -m "UPDATING K8S Yaml From CI [ci skip]" 
            git push https://$GIT_USER:$GIT_PASSWORD@github.com/yanivomc/docker-piplines.git



      - store_test_results:
          path: ./TestResults
