---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: piplineapp-demo
  labels:
    appl: piplineapp-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      appl: piplineapp-demo
  template:
    metadata:
      labels:
        appl: piplineapp-demo
    spec:
      containers:
      - name: piplineapp-client-demo
        image: yanivomc/piplineapp:latest